application: enchantedforest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /static/images
  static_dir: static/images

- url: /static/spriteinfo
  static_dir: static/spriteinfo

- url: /static/sounds
  static_dir: static/sounds
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"

